# Generated by Django 5.1.1 on 2024-10-03 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryActivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceChange', models.FloatField(default=0.0)),
                ('CompleteTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('type', models.CharField(blank=True, max_length=100)),
                ('AccountBalance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accountbalance')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_activates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('creatAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, upload_to='account/static/')),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(default=100)),
                ('number_of_content', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
