# Generated by Django 5.1.1 on 2024-10-03 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('enhanced_content', models.TextField(blank=True)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.DateTimeField(blank=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_data', models.DateTimeField(blank=True)),
                ('state', models.TextField(default='waiting for accept')),
                ('total_money', models.FloatField(default=0.0)),
                ('money_per_user', models.FloatField(default=0.0)),
                ('max_accept_user', models.IntegerField(default=1)),
                ('push_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpcontent_push_users', to=settings.AUTH_USER_MODEL)),
                ('unverified_accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpcontent_unverified_users', to=settings.AUTH_USER_MODEL)),
                ('verified_accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpcontent_verified_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('enhanced_content', models.TextField(blank=True)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.DateTimeField(blank=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('state', models.TextField(default='waiting for accept')),
                ('max_accept_user', models.IntegerField(default=1)),
                ('push_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportcontent_push_users', to=settings.AUTH_USER_MODEL)),
                ('unverified_accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportcontent_unverified_users', to=settings.AUTH_USER_MODEL)),
                ('verified_accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportcontent_verified_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
