# Generated by Django 5.1.1 on 2024-09-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
